### ISSUE TITLE
Add semver to node dependencies

### ISSUE THREAD

**Issue by pmgm** [unimelb/pattern-lib#957]
Webpack uses semver versioning. I would like to use the semver package (https://docs.npmjs.com/misc/semver) to check and increment the versioning safely and automatically in a git pre-push hook (see JIRA issue https://jira.unimelb.edu.au/browse/TS-90). Please add semver to the pattern-lib dependencies so that I can guarantee it will available for the hook to work.

## Expected behaviour
semver package is downloaded and installed upon 
yarn build

## Current behaviour
1. ubuntu@nodebox:~/pattern-lib$ node -e "semver.valid('1.2.3')"
[eval]:1
semver.valid('1.2.3')
^

ReferenceError: semver is not defined
    at [eval]:1:1
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at evalScript (internal/bootstrap/node.js:586:27)
    at startup (internal/bootstrap/node.js:264:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

### Affected browsers
This is a backend function to do with package.json.version so browsers not required

**Comment by pmgm** [comment]
Expected solution:

yarn add semver

**Comment by pmgm** [comment]
Closed by unimelb/pattern-lib#966
